# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [187]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [188]:
vector_10to49= np.arange(10,50)
vector_10to49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
vector_10to49.shape

(40,)

5. Print the type of the previous array in question 3

In [190]:
vector_10to49.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [10]:
print(np.__version__)

1.18.1


In [15]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Paco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Paco/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Paco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:

7. Print the dimension of the array in question 3


In [16]:
vector_10to49.ndim

1

8. Create a boolean array with all the True values

In [194]:
arr_bool = np.ones((5), dtype=bool)
arr_bool

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [26]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

10. Create a three dimensional array



In [27]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [6]:
n_array = np.array([1,2,3,4,5,6,7,8,9])
reveresed_array = n_array[::-1]
reveresed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [197]:
null_v = np.zeros(10)
null_v[4] = 1
null_v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [10]:
eye_mat = np.eye(3,3)
eye_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [18]:
arr = np.array([1,2,3,4,5])
arr.astype(np.float64)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [27]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])
result = np.multiply(arr1, arr2)
result

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])
result = np.where(arr1 > arr2, arr1, arr2)
result

array([[ 1,  4,  3],
       [ 7,  5, 12]])

17. Extract all odd numbers from arr with values(0-9)

In [37]:
n_array = np.arange(10)
odd_array = n_array[n_array%2 == 1]
odd_array

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [39]:
n_array = np.arange(10)
minus_array = np.where(n_array%2 == 1, -1, n_array)
minus_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [199]:
arr = np.arange(10)
arr[5:9]= 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [55]:
array_2d = np.ones((5,5))
array_2d
array_2d[1:4,1:4]=0
array_2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [57]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1,1]= 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [201]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0,:,:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [202]:
arr_2d = np.array([[0,1,2], [3,4,5],[6,7,8]])
sliced_arr = arr_2d[0:1, :]
sliced_arr

array([[0, 1, 2]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [203]:
arr_2d = np.array([[0,1,2], [3,4,5],[6,7,8]])
sliced_arr = arr_2d[1:2,1:2]
sliced_arr

array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [204]:
arr_2d = np.array([[0,1,2], [3,4,5],[6,7,8]])
sliced_arr = arr_2d[0:2,2:3]
sliced_arr

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [210]:
arr_rand = np.random.randn(10,10)
arr_rand

array([[ 0.59484895,  1.87118946,  0.59143824, -1.24658005,  1.38736479,
         1.10911272, -0.27809283,  0.60186257,  0.17293954,  0.75822351],
       [-1.562007  , -0.89585647, -1.56258719,  0.82007065, -0.75295448,
         0.884105  , -2.08383117, -0.25328739,  1.85320964, -1.52704555],
       [-0.01426417,  0.67699296, -0.96275132,  0.19898272,  0.04915491,
        -0.1247631 , -0.48698997, -0.15610034,  0.40025334, -0.53600693],
       [ 0.20959708, -0.38527189, -0.45041269, -1.21624779, -0.29615951,
         1.09763116,  0.26852071,  0.2557077 ,  2.88015671, -0.89153143],
       [-1.27446214, -0.94997603,  1.10367597, -1.23280705, -0.35636007,
         1.48062591,  0.80118438, -0.74149347,  0.15264841,  0.74602467],
       [ 0.29164532,  1.66246988,  1.27155621,  0.00536037,  0.0775708 ,
         0.64086205, -0.31779097, -1.90893391, -0.30139901, -0.8863291 ],
       [-0.55655866, -0.41572339,  0.9372592 ,  0.77995056,  1.24894005,
        -0.32103949,  2.19131824, -1.02477618

In [211]:
minimum_value = arr_rand.min()
maximum_value = arr_rand.max()
print(f"minimum value is = {minimum_value}")


minimum value is = -2.083831169604005


In [212]:
print(f"maximum value is = {maximum_value}")

maximum value is = 2.880156711646908


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [85]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_val = np.intersect1d(a, b)
common_val

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [215]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
match = np.where(a == b)
match

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [110]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
data

array([[-0.14894096,  0.86930687, -0.4291029 , -2.10483827],
       [ 0.40507888, -1.5367651 , -0.80138437,  0.14085737],
       [ 0.04734409, -1.29582345, -1.19875772,  0.85733797],
       [ 0.68603201,  0.83296089, -0.85077178,  1.41415263],
       [-0.06102033,  2.01056323, -0.67488813, -0.55605497],
       [-0.19993375, -0.45284348,  0.23022074,  2.26247102],
       [-0.10590077, -0.16372766,  0.57052751,  0.19866223]])

In [114]:
values = data[np.where(names != 'Will')]
values

array([[-0.14894096,  0.86930687, -0.4291029 , -2.10483827],
       [ 0.40507888, -1.5367651 , -0.80138437,  0.14085737],
       [ 0.68603201,  0.83296089, -0.85077178,  1.41415263],
       [-0.19993375, -0.45284348,  0.23022074,  2.26247102],
       [-0.10590077, -0.16372766,  0.57052751,  0.19866223]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [115]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
data

array([[-1.22859959, -0.5491642 , -0.38896263, -0.50709612],
       [-0.70900888, -1.20568451, -1.23574649,  0.51840407],
       [ 0.69049737,  0.54968241,  0.83653069, -0.97155295],
       [ 0.85112992, -0.42096301,  0.96900356, -2.48519343],
       [-1.69785888, -1.0630586 ,  0.0858953 , -1.60973253],
       [ 2.09837231,  0.91625458, -0.89591802,  0.11817468],
       [ 0.78231325,  1.0038798 , -1.50747859,  1.44468808]])

In [118]:
values = data[np.where((names != 'Will') & (names != 'Joe'))]
values

array([[-1.22859959, -0.5491642 , -0.38896263, -0.50709612],
       [ 0.85112992, -0.42096301,  0.96900356, -2.48519343]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [132]:
arr_1to_15 = np.arange(1,16).reshape((5,3))
arr_1to_15

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [133]:
arr_3d = np.arange(1,17).reshape((2,2,4))
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [221]:
swapped = arr_3d.swapaxes(1,2)
swapped

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [223]:
arr_10 = np.arange(10)
arr_sqrt = np.sqrt(arr_10)
arr_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [156]:
replaced = np.where(arr_sqrt < 0.5, 0, arr_sqrt)
replaced

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [170]:
a_array = np.random.randn((12))
b_array = np.random.randn((12))
max_val = np.maximum(a_array, b_array)
max_val

array([ 0.34558098, -0.1465621 ,  0.75135229,  1.40567937,  0.91224861,
        1.45379211,  1.74673404,  1.38982548,  0.99258293,  0.21604527,
        0.32893275,  1.15388406])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [174]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
sorted_unique = np.sort(unique_names)
sorted_unique

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [176]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
removed_elements = np.setdiff1d(a, b)
removed_elements

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [177]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
new_array = np.delete(sampleArray, 2, axis=1)
new_array


array([[34, 43],
       [82, 22],
       [53, 94]])

In [180]:
newColumn = np.array([[10,10,10]])
inserted_col_array = np.insert(new_array, 2, newColumn, axis=1)
inserted_col_array

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [181]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_product = np.dot(x, y)
dot_product

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [185]:
matrix = np.random.randn(20)
matrix

array([ 1.78194415,  0.37429186, -0.83127671, -0.24631783,  0.44332976,
        0.28596747, -1.4831561 ,  0.7963367 , -0.09737724, -0.00402769,
        0.29625878, -0.92691761,  0.58650341,  0.1373844 ,  0.65894363,
       -0.29910426,  0.71522304,  1.98174434, -0.37649527, -0.28480841])

In [186]:
cumulative_sum = np.cumsum(matrix)
cumulative_sum

array([1.78194415, 2.15623601, 1.32495929, 1.07864146, 1.52197122,
       1.80793869, 0.32478259, 1.12111929, 1.02374204, 1.01971436,
       1.31597314, 0.38905553, 0.97555894, 1.11294334, 1.77188697,
       1.47278271, 2.18800575, 4.16975009, 3.79325482, 3.50844641])